// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4-fOfJ-5PHV4Zp_ZftrDlRTO9JmvK8Cs',
    appId: '1:436445555569:web:246cf1b82bb436ff0224d0',
    messagingSenderId: '436445555569',
    projectId: 'snakegame-911c8',
    authDomain: 'snakegame-911c8.firebaseapp.com',
    storageBucket: 'snakegame-911c8.appspot.com',
    measurementId: 'G-88ZKTPL2Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBaNs5Xk1-5-3TZSL_H1v7CA8TFRek_g',
    appId: '1:436445555569:android:c445439bf5e3db730224d0',
    messagingSenderId: '436445555569',
    projectId: 'snakegame-911c8',
    storageBucket: 'snakegame-911c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8prC_EU0jceN8-8y9PfE6zoCjiT5OhZg',
    appId: '1:436445555569:ios:f0c6a012386add2f0224d0',
    messagingSenderId: '436445555569',
    projectId: 'snakegame-911c8',
    storageBucket: 'snakegame-911c8.appspot.com',
    iosClientId: '436445555569-hq17o43ivt99v6ct4kd1me0niaitsk3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGame',
  );
}
